In [ ]:
import tensorflow as tf
print(tf.__version__)

In [2]:
mnist = tf.keras.datasets.mnist

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
len(x_train)

In [5]:
from matplotlib import pyplot as plt

In [ ]:
x_train[10]

In [ ]:
plt.imshow(x_train[3333], cmap='gray')
plt.show()

In [ ]:
y_train[3333]

In [11]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10)
])

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
res = model(x_train[3333:3334])
print(res)

In [24]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=8)

In [ ]:
import numpy as np

In [ ]:
y_train[600]

In [ ]:
plt.imshow(x_train[10000], cmap='gray')
plt.show()

In [ ]:
tf.argmax(model(x_train[10000:10001]), axis=1)

In [ ]:
plt.imshow(x_test[100], cmap='gray')
plt.show()

In [ ]:
test = x_test[100:102]

In [ ]:
test.shape

In [ ]:
predictions = model(x_test[100:110])

In [ ]:
predictions

In [ ]:
tf.argmax(predictions, axis=1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([6, 0, 5, 4, 9, 9, 2, 1, 9, 4])>

In [ ]:
y_test[990:1000]

array([2, 3, 9, 0, 1, 2, 2, 0, 8, 9], dtype=uint8)

In [ ]:
plt.imshow(x_test[990], cmap='gray')
plt.show()

In [ ]:
loss_fn(y_test[990:1000], predictions)

<tf.Tensor: shape=(), dtype=float32, numpy=1.4614406>

Train and evaluate your model

In [ ]:
model.evaluate(x_test,  y_test)

In [ ]:
print(y_test[:5])

In [ ]:
test_prediction = model(x_test[:5])

In [ ]:
print(tf.argmax(test_prediction, axis=1))

tf.Tensor([7 2 1 0 4], shape=(5,), dtype=int64)


In [36]:
from google.colab import drive
drive.mount('/content/drive')
%cd drive/MyDrive/Computer Vision/1.Classification - MNIST
%ls

Mounted at /content/drive
/content/drive/MyDrive/Computer Vision/1.Classification - MNIST
'Classifier - MNIST - Beginner.ipynb'   mnis_7.png  'mnist_5 (1).png'
 mnis_2.png                             mnis_8.png   mnist_5.png


In [37]:
from PIL import Image
from io import BytesIO

In [38]:
loaded_image = Image.open("mnis_2.png")

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving mnist_5.png to mnist_5 (1).png


In [ ]:
loaded_image = Image.open(BytesIO(uploaded['mnist_5.png']))

In [39]:
loaded_image

In [40]:
import numpy as np

In [41]:
loaded_image = loaded_image.resize((28,28))

In [ ]:
np.array(loaded_image).shape

In [42]:
loaded_image = loaded_image.convert('L')

In [43]:
loaded_image

In [44]:
l_image = np.array(loaded_image)

In [45]:
l_image.shape

(28, 28)

In [46]:
l_image = np.expand_dims(l_image, axis=0)

In [47]:
l_image.shape

(1, 28, 28)

In [48]:
l_image = l_image / 255.0

In [50]:
l_prediction = model(l_image)

In [51]:
l_prediction

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ -5.879214 ,  -2.611976 ,   4.152328 ,   3.475482 ,  -8.959684 ,
         -1.8514063,  -1.8437382,  -8.381254 , -10.4869   , -24.612469 ]],
      dtype=float32)>

In [ ]:
print(tf.argmax(l_prediction, axis=1).numpy())

[3]


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(10, (3, 3), activation='relu', input_shape=(28, 28, 1)),
  tf.keras.layers.Flatten(input_shape=(26, 26, 10)),
  tf.keras.layers.Dense(128, activation='relu'),
  #tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10),
  #tf.keras.layers.Softmax()
])